# Generated by Django 5.2.13 on 2026-05-31 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Full consultation fee paid by patient', max_digits=10)),
                ('commission_percentage', models.DecimalField(decimal_places=2, help_text='Platform commission % at time of booking (snapshot)', max_digits=5)),
                ('commission_fee', models.DecimalField(decimal_places=2, help_text='Platform commission amount = total_amount * (commission_percentage / 100)', max_digits=10)),
                ('doctor_payout', models.DecimalField(decimal_places=2, help_text='Net amount payable to doctor = total_amount - commission_fee', max_digits=10)),
                ('payment_method', models.CharField(default='Online card', max_length=50)),
                ('card_last4', models.CharField(blank=True, max_length=4, null=True)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Refunded', 'Refunded'), ('Partially_Refunded', 'Partially Refunded')], default='Completed', max_length=20)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
        migrations.CreateModel(
            name='PlatformConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=10.0, help_text='Platform commission percentage (e.g., 10.00 means 10%)', max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Configuration',
                'verbose_name_plural': 'Platform Configuration',
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_amount', models.DecimalField(decimal_places=2, help_text='Amount refunded to patient (equals total_amount — full refund policy)', max_digits=10)),
                ('commission_retained', models.DecimalField(decimal_places=2, default=0.0, help_text='Commission amount retained by platform (0.00 for full refund policy)', max_digits=10)),
                ('reason', models.TextField(blank=True, null=True)),
                ('initiated_by', models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor'), ('admin', 'Admin')], max_length=10)),
                ('refunded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Refund',
                'verbose_name_plural': 'Refunds',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='cancelled_by',
            field=models.CharField(blank=True, choices=[('patient', 'Patient'), ('doctor', 'Doctor'), ('admin', 'Admin')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor_payout',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Net doctor payout after commission', max_digits=10),
        ),
        migrations.AddField(
            model_name='appointment',
            name='platform_commission_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Commission amount deducted', max_digits=10),
        ),
        migrations.AddField(
            model_name='appointment',
            name='platform_commission_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Commission % snapshot at booking time', max_digits=5),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='doctoravailability',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='doctorslot',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userotp',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['patient', 'status'], name='clinic_appo_patient_845bfe_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['doctor', 'status'], name='clinic_appo_doctor__9fdbcd_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['payment_status'], name='clinic_appo_payment_7324d1_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['created_at'], name='clinic_appo_created_dd3574_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorslot',
            index=models.Index(fields=['doctor', 'date'], name='clinic_doct_doctor__b30e97_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorslot',
            index=models.Index(fields=['is_booked'], name='clinic_doct_is_book_f19b48_idx'),
        ),
        migrations.AddConstraint(
            model_name='doctorslot',
            constraint=models.UniqueConstraint(fields=('doctor', 'date', 'time'), name='unique_doctor_date_time_slot'),
        ),
        migrations.AddField(
            model_name='payment',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_record', to='clinic.appointment'),
        ),
        migrations.AddField(
            model_name='refund',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refund_record', to='clinic.appointment'),
        ),
        migrations.AddField(
            model_name='refund',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refund', to='clinic.payment'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['appointment'], name='clinic_paym_appoint_7d7ea7_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='clinic_paym_status_12d5d4_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['paid_at'], name='clinic_paym_paid_at_02f377_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['appointment'], name='clinic_refu_appoint_967a29_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['refunded_at'], name='clinic_refu_refunde_134665_idx'),
        ),
    ]
