# Generated by Django 5.2.13 on 2026-05-31 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_payment_platformconfig_refund_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, help_text='Stripe PaymentIntent ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='stripe_refund_id',
            field=models.CharField(blank=True, help_text='Stripe Refund ID', max_length=255, null=True),
        ),
    ]
